name: news_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.18.1
  page_transition: ^2.0.9
  provider: ^6.0.5
  reading_time: ^2.0.0
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/launch_image.png
  android_12: 
    image: assets/launch_image.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
